title: Hossain Quantum Research
description: Computational Materials, AI/ML, and Quantum Algorithms

url: https://hossain-cq.github.io
baseurl: ""

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:name/

  projects:
    output: true
    permalink: /projects/:name/

  publications:
    output: true
    permalink: /publications/:name/
